### ISSUE TITLE
Example "engage" endpoint documentation

### ISSUE THREAD

**Issue by afgarcia86** [keolo/mixpanel_client#50]
https://mixpanel.com/docs/api-documentation/data-export-api#engage-default

I guess this isn't technically an issue but I am hoping you can explain how I would use the engage endpoint? How would I properly pass a value in the where field?

ex: I want to query for a user that has the ID that equals X

**Comment by keolo** [comment]
I haven't tried it but I'd imagine it'd be something like this:

    client = Mixpanel::Client.new(
      api_key:    'changeme',
      api_secret: 'changeme'
    )

    data = client.request(
      'engage',
      where: 'expression'
    )

**Comment by afgarcia86** [comment]
Ah I figured, I am still have trouble properly writing the expression, not on you but the mix panel docs are not super clear to me as a more novice developer. If you are familiar with it mind writing a sample expression?

Andres Garcia

Sent from
https://polymail.io/

On Tue, Jun 28, 2016 at 12:36 PM Keolo Keagy

<
mailto:Keolo Keagy <notifications@github.com>
> wrote:

I haven't tried it but I'd imagine it'd be something like this:

client = Mixpanel::Client.new( api_key: 'changeme', api_secret: 'changeme' ) data = client.request( 'engage', where: 'expression' )

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/keolo/mixpanel_client/issues/50#issuecomment-229106457
, or
https://github.com/notifications/unsubscribe/ADcGJQnqTSP5cNc6dQenNqVOvkuH2zAVks5qQU2XgaJpZM4JASBc
.

https://github.com/keolo/mixpanel_client/issues/50#issuecomment-229106457

**Comment by keolo** [comment]
I'm not familiar with the syntax of the expression unfortunately. However, if you find the solution, feel free to post it here.

**Comment by agirlnamedsophia** [comment]
@afgarcia86 I have found this to work for me: 
```
props = [ (properties[\"uid\"] == \"#{mixpanel_id_a}\") or (properties[\"uid\"] == \"#{mixpanel_id_b}\") ]

parameters = { 'selector' => props }
client.request('engage', parameters)
```
