### ISSUE TITLE
SSL Error calling client request

### ISSUE THREAD

**Issue by jbrunson** [keolo/mixpanel_client#51]
When I run this code requesting data from mixpanel, I get this error.  I have updated openssl, reinstalled ruby with rvm, added the ca-cert.pem to my SSL_CERT_FILE and nothing has worked.

```client = Mixpanel::Client.new(api_key: 'API_KEY', api_secret: 'API_SECRET')
client.request('export', { event: ['EVENT'] , 'where' => 'properties["metric_id"]==1432346', from_date: '2016-06-13', to_date: '2016-06-13'})```


Errors:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

from /Users/user/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:920:in `connect'

**Comment by keolo** [comment]
This sounds like a ssl configuration issue unrelated to mixpanel_client. Let me know if you're able to isolate this problem to only this gem.
