### ISSUE TITLE
error occured while installing typheous -v 0.3.3 , and Bundler cannot continue.

### ISSUE THREAD

**Issue by Saran-S** [keolo/mixpanel_client#64]
Hi,

I am facing this error while doing **bundle install**.

**An error occurred while installing typhoeus (0.3.3), and Bundler cannot continue.
Make sure that `gem install typhoeus -v '0.3.3'` succeeds before bundling.**

typheous 0.3.3 is an older version and it is deprecated and I could not install it. Can anyone please help.

Thanks.

**Comment by keolo** [comment]
Hi Saran, this should be fixed in the latest version (5.0.0).
